version: "3"
services:
    order_api:
        image: "deftnt/order_api"
        ports:
            - "8080:80"
        restart: always
        depends_on:
            - db
    rating_api:
        image: "deftnt/rating_service"
        ports:
            - "8081:80"
        restart: always
        depends_on:
            - db
    receipt_api:
        image: "deftnt/receipt_service" 
        ports:
            - "8082:80"
        depends_on:
            - db       
    db:
        image: "microsoft/mssql-server-linux"
        hostname: 'sqlserver'
        environment:
            SA_PASSWORD: "ThisIsPass1@"
            ACCEPT_EULA: "Y"
        restart: always
